"""files builds simlogs hazardstats

Revision ID: 995335956c96
Revises: 587c700fe05d
Create Date: 2026-04-22 16:07:03.182126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995335956c96'
down_revision: Union[str, None] = '587c700fe05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_table('builds',
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('binary_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='build_status', native_enum=False, length=16), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('build_id')
    )
    op.create_index(op.f('ix_builds_file_id'), 'builds', ['file_id'], unique=False)
    op.create_table('sim_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=True),
    sa.Column('cpi_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.build_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_sim_logs_build_id'), 'sim_logs', ['build_id'], unique=False)
    op.create_table('hazard_stats',
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('hazard_type', sa.String(length=32), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['sim_logs.log_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_index(op.f('ix_hazard_stats_log_id'), 'hazard_stats', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hazard_stats_log_id'), table_name='hazard_stats')
    op.drop_table('hazard_stats')
    op.drop_index(op.f('ix_sim_logs_build_id'), table_name='sim_logs')
    op.drop_table('sim_logs')
    op.drop_index(op.f('ix_builds_file_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
